spring:
  application:
    name: stream-dev

  # --- DATABASE CONFIGURATION ---
  datasource:
    # Change this URL to your Neon/Supabase link, or your local Postgres DB
    url: jdbc:postgresql://localhost:5432/tutoring_db
    username: postgres
    password: your_password_here
    driver-class-name: org.postgresql.Driver

  # --- JPA / HIBERNATE SETTINGS ---
  jpa:
    hibernate:
      # 'update' tells Spring to automatically create the 'users' table based on your User.java class
      ddl-auto: update
    show-sql: true # Prints the SQL queries in your console so you can see what's happening
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: #your port_number